traffic <- read.csv(file = '/Users/administrator/desktop/stat479_proj/daily.csv',stringsAsFactors = TRUE)
traffic$traffic_volume
plot(traffic$traffic_volume,type = "l")
summary(traffic$traffic_volume)
acf(traffic$traffic_volume, lag.max = 100)
linear_md = lm(traffic$traffic_volume ~ traffic$holiday + traffic$temp +traffic$rain_1h +traffic$snow_1h+traffic$clouds_all)
abline(linear_md, col="red")
summary(linear_md)

resid(linear_md)
plot(resid(linear_md), type='l')
acf(resid(linear_md), lag.max = 100)
adf.test(resid(linear_md))
adf.test(traffic$traffic_volume)
library(forecast)
install.packages("TSA")
library(tseries)
library(TSA)
ar(traffic$traffic_volume)
Box.test(traffic$traffic_volume, lag=1, type="Box-Pierce")
library(lmtest)
Box.test(resid(linear_md), lag=1, type="Box-Pierce")
pacf(traffic$traffic_volume, lag.max = 100)
ar(traffic$traffic_volume, aic = TRUE)
summary(ar(traffic$traffic_volume, aic = TRUE))
Box.test(ar_md$resid, fitdf = 28, lag = 29)
best_arima_2 <-auto.arima(traffic$traffic_volume, max.p = 40, max.q = 40, max.d = 40)
best_arima_1 <-auto.arima(traffic$traffic_volume)
sum(best_arima_1$residuals ^2 )
sum(best_arima_2$residuals ^2)
season_model <- Arima(traffic$traffic_volume, order= c(30, 0, 0), seasonal = list(order = c(0, 0, 1), period=7))
diff_season <- Arima(traffic$traffic_volume, order= c(30, 1, 0), seasonal = list(order = c(0, 0, 1), period=6))
